kod od płytki
KNR-PW/hangwatch pull request #15
Opened 2023-12-08 19:23 UTC by OlgierdIwaniuk

tu jest kod od płykti ale jeszcze bez migania jeżeli serwer nie odpowiada.

2023-12-08 19:24 UTC, OlgierdIwaniuk commented
to jest kod od płytki ale bez migania jeżeli serwer nie odpowiada

2023-12-08 21:47 UTC, OlgierdIwaniuk commented
To teraz światło miga jeżeli nie ma połączenia z serwerem ,ale nie uwzględnia to sytuacji że serwer zostanie odpalony podczas zawieszenia kluczy . trzeba zdjąć klucze i jeszcze raz je nałożyć.

2023-12-09 10:15 UTC, pktiuk commented on README.md
>  Możliwa jest również sytuacja kiedy pojawi się awaria. Wtedy na stronie pojawi się informacja
W tym pull requeście nie powinno być chyba commitów, które zmieniają README.  

Masz z tego powodu konflikty. (w git graphie możesz kliknąć na wybrane commity i wybrać opcję `Drop Commit`)

2023-12-09 10:15 UTC, pktiuk commented on arduino/src/main.cpp
> +    int przyciskState = digitalRead(25);
Nie powinno używać się polskich słów w zmiennych

2023-12-09 10:17 UTC, pktiuk commented on arduino/src/main.cpp
> +                digitalWrite(33, HIGH);
Zamiast mieć w kodzie zapisane kilkanaście razy numer wybranego pina (np 33) trzeba na początku ustawić jakiegoś consta, albo define'a i potem z niego korzystać np `#define BUTTON_PIN 99` albo `const int LED_PIN=100`

2023-12-09 10:20 UTC, pktiuk requested changes
Kilka rzeczy do poprawy

2023-12-11 12:25 UTC, closed without merging