poprawione readme
KNR-PW/hangwatch pull request #4
Opened 2023-11-02 18:57 UTC by OlgierdIwaniuk

#1
uwzględniłem twoje uwagi. Teraz opis jest krótszy i nie opisuje dokładnie poszczególnych funkcji

2023-11-28 08:18 UTC, OlgierdIwaniuk commented
Co zmienić w tym readme ? 
brakuje czegoś w samym opisie czy jakiś zdjęć modelu ?

2023-11-28 11:40 UTC, pktiuk requested changes
Potrzebne zmiany opisałem w wątkach. POszczególne zagadnienia omawiajmy w ramach przydzielonych wątków. Jak już coś rozwiązesz/naprawisz to po rpostu zamykamy ten wątek aby nie było spamu.

Poza tym polecam trochę zapoznać się z markdownem, aby wiedzieć, jak wrzucać ładnie sformatowany tekst https://stackedit.io/

2023-11-28 11:40 UTC, pktiuk commented on README.md
> + # Działanie strony
Wszystkie nagłówki poza tym pierwszym tytułowym powinny być poziomu drugiego h2., czyli powinno być tutaj i poniżej `##` zamiast `#`

```suggestion
 ## Działanie strony
```

2023-11-28 11:40 UTC, pktiuk commented on README.md
> +
Brakuje tutaj instrukcji uruchomienia całości.

Potrzebny też jest opis endpointów (czyli np. "pod adresem /getstatus/ otrzymujemy informację o haczyku, która wygląda tak: i tutaj np wklejona przykładowa wiadomość w jsonie, którą możemy dostać).

2023-11-29 07:52 UTC, OlgierdIwaniuk commented
wieczorem podeśle ci już ze wszystkimi zmianami , z dodanymi endpointami i opisem uruchomienia całości

2023-11-29 17:10 UTC, pktiuk commented on README.md
> + Obsługuje żądanie typu GET i jest domyślną stroną "stroną internetową" . Pobiera i renderuje "index.html" z przekazaną informacją o stanie GPIO.
Jest już prawie dobrze. Tylko musisz jeszcze poprawić formatowanie.   
Widzę, że zamierzałeś umieścić opisy w nowych linijkach, ale nie dodałeś odpowiednich odstępów, aby to wyglądało tak, jak trzeba (albo spacja na końcu, aby był enter, albo enter odstępu, aby był nowy paragraf`

2023-11-29 17:20 UTC, pktiuk commented on README.md
> + *GPIO state: {'gpioState': 'offline'}*
Poza tym nie do końca podoba mi się ten endpoint. Czemu nazwałeś go w ten sposób?   
Nazwa powinna mówić o czym informuje cię serwer, a nie jak jest zbudowane urządzenie.

Nazwa endpointa powinna brzemieć jak coś w stylu `/hook_states`, albo `/hooks`.

2023-11-29 17:21 UTC, pktiuk requested changes
Nadal są rzeczy do poprawy. Trzeba chyba dokładniej zastanowić się nad tym, jak ma być zbudowany system, do czego ma służyć i jak docelowo powinien działać.

2023-11-29 17:25 UTC, pktiuk commented on README.md
> + *GPIO state: {'gpioState': 'offline'}*
Inną kwestią jest to, że docelowo ma być możliwość obsługiwania kilku haczyków.

W związku z tym odpowiedźź z tego endpointa powinna wyglądać jakoś tak

```json
[
    {
        "name": "warsztat027",
        "state": "empty"
    },
    {
        "name": "boks_ITC",
        "state": "offline"
    },
]
```
Może być kilka haczyków i mogą mieć one kilka stanów: `offline` - czyli kontakt się zerwał `empty` - brak kluczy, `hanged` - klucze wiszą na nim

2023-11-29 21:42 UTC, OlgierdIwaniuk commented
poprawiłem to formatowanie i użyłem bloku kodu .

2023-11-29 21:47 UTC, OlgierdIwaniuk commented on README.md
> + *GPIO state: {'gpioState': 'offline'}*
> Poza tym nie do końca podoba mi się ten endpoint. Czemu nazwałeś go w ten sposób? Nazwa powinna mówić o czym informuje cię serwer, a nie jak jest zbudowane urządzenie.
> 
> Nazwa endpointa powinna brzemieć jak coś w stylu `/hook_states`, albo `/hooks`.

W sumie nazwa została z wcześniejszego etapu pisania kodu kiedy to do get_gpio_state miała płytka wysyłac informacje.
Ale to zawsze moge zmienić nazwę tego endpointa.

2023-11-29 21:48 UTC, OlgierdIwaniuk commented
> Nadal są rzeczy do poprawy. Trzeba chyba dokładniej zastanowić się nad tym, jak ma być zbudowany system, do czego ma służyć i jak docelowo powinien działać.

Chyba będzie trzeba się spotkać i zastanowić jak to powinno działać

2023-12-02 19:32 UTC, pktiuk commented on README.md
> +
Brakuje tutaj poprawnego formatowania dla markdowna.
```suggestion
```json
{
     "name": "warsztat027",
     "state": "hanged"
}
```
```

2023-12-02 19:32 UTC, pktiuk commented on README.md
> +
Trzeba poprawić tego jsona i pozostałe

2023-12-02 19:34 UTC, pktiuk commented on README.md
> + Jeżeli w sali znajduje się ktoś i powiesił klucze na haczyku to na stronie internetowej pojawia się wartość
Strona internetowa jest niepotrzebna. Mają być ylko endpointy

2023-12-02 19:34 UTC, pktiuk commented on README.md
> + 2.  **Endpoint *"/hook_state"***
Jaki jest cel tego endpointa, skoro te  same informacje są już na endpoincie hooks?

2023-12-02 19:35 UTC, pktiuk commented on README.md
> + 3. **Endpoint"*/hook_offline*"**
Po co oddzielny endpoint do pokazywania stanu offline?

2023-12-02 20:04 UTC, OlgierdIwaniuk commented on README.md
> + 2.  **Endpoint *"/hook_state"***
czyli tak naprewdę wystarczy jeden endpoint ?

2023-12-02 20:36 UTC, pktiuk commented on README.md
> + 2.  **Endpoint *"/hook_state"***
Tak. 
endpoint `/hooks`
metoda GET do sprawdzania statusu, a POST do aktualizowania statusów (używana tylko przez haczyki)

2023-12-02 20:45 UTC, OlgierdIwaniuk commented on README.md
> + 2.  **Endpoint *"/hook_state"***
ok

2023-12-02 21:48 UTC, pktiuk approved these changes
Wszystko na ten moment wygląda git.

2023-12-02 21:49 UTC, merged