Dioda
KNR-PW/hangwatch pull request #5
Opened 2023-11-27 13:40 UTC by OlgierdIwaniuk

dodaliśmy w modelu dwie diody jedna włącza się jeżeli na haczyku powiesimy klucze ,druga jak informacja ta zostanie wysłana na stronę internetową .

2023-11-27 14:01 UTC, pktiuk commented
@OlgierdIwaniuk  Czemu nie dokończyłeś poprzednich zadań?

2023-11-27 21:30 UTC, OlgierdIwaniuk commented
> @OlgierdIwaniuk Czemu nie dokończyłeś poprzednich zadań?

Problemy z czytaniem ze zrozumieniem

2023-11-27 22:40 UTC, pktiuk commented
Dopóki Pull Request nie jest zmergowany zadanie jest uznawane za niezrobione.    
Poza tym zalecałem ci też robienie rzeczy regularnie małymi kawałkami, czyli robisz jeden pull request z poprawkami Readme, drugi z poprawkami w kodzie ESP, a np. trzeci z poprawionym kodem pythonowym

2023-12-02 21:50 UTC, pktiuk commented on arduino/src/main.cpp
>  void setup(){
Masz tutaj niechący zacommitowane linijki z notatkami.

2023-12-02 21:51 UTC, pktiuk requested changes
Ten kod ci się nie skompiluje.

2023-12-08 19:25 UTC, closed without merging